using System;
namespace Tiny_TypeScript.Core
{
    public enum TokenType
    {
       Plus,
       Minus,
       Equal,
       Colon,
       Semicolon,
       LogicalAnd,
       LogicalOr,
       LeftParens,
       RightParens,
       Multiplication,
       Division,
       GreaterThan,
       LessThan,
       GreaterOrEqualThan,
       LessOrEqualThan,
       LeftBracket,
       RightBracket,
       LeftBrace,
       RightBrace,
       Comma,
       IfKeyword,
       WhileKeyword,
       ElseKeyword,
       NumberKeyword,
       Identifier,
       StringKeyword,
       EOF,
       StringLiteral,
       NumberLiteral,
       ArrayKeyword,
       PrintKeyword,
       BasicType,
       ComplexType,
       BoolKeyword,
       TrueKeyword,
       FalseKeyword
    }
}
